### ISSUE TITLE
whole dataset download

### ISSUE THREAD

**Issue by lastdawnsu** [zjunlp/FactCHD#2]
The entire dataset cannot be downloaded. How to get it?

**Comment by njcx-ai** [comment]
Thanks for your attention. We have provided a specific Google Drive download link in the data format column for FactCHD.

**Comment by lastdawnsu** [comment]
> Thanks for your attention. We have provided a specific Google Drive download link in the data format column for FactCHD.

I applied, but there was no response

**Comment by njcx-ai** [comment]
Sorry, I didn't notice the permission issue before. Sharing permissions have now been turned on.
