### ISSUE TITLE
About the Evaluation

### ISSUE THREAD

**Issue by XiangyanChen** [zjunlp/FactCHD#3]
After inference, I got the result file. I thought two files, the original and the result one, were enough to get a score. But after I ran "evaluate/score.py", I found two files("path1", "base_path2", "path3") are needed to provide. I think "base_path2" and "path3" indicate the result file and original test file, so I don't know much about what "path1" means.

**Comment by njcx-ai** [comment]
Hello, thank you for your interest in our work. We apologize for the unclear parameter description. "path1" and "base_path2" respectively indicate the original test file and result file, while "path3" represents the test data converted to training set format. We will update the data format corresponding to "path3" in evaluate/score.py.
